-- 1. Retrieve the names and locations of restaurants with a rating of 4.5 or higher.
select name, city from restaurants where rating >= 4.5;

-- 2. Find the total number of orders placed by each customer.
select customerid, count(*) as total_orders from orders group by customerid;

-- 3. List all restaurants offering "italian" cuisine in "mumbai".
select name from restaurants where cuisinetype = 'Italian' and city = 'Mumbai';

-- 4. Calculate the total revenue generated by each restaurant from completed orders.
select restaurantid, sum(orderamount) as total_revenue from orders where orderstatus = 'Delivered' group by restaurantid;

-- 5. Retrieve the most recent order placed by each customer.
select customerid, max(orderdate) as recent_order from orders group by customerid;

-- 6. List customers who have not placed any orders yet.
select c.firstname, c.lastname from customers c left join orders o on c.customerid = o.customerid where o.orderid is null;

-- 7. Identify the most reviewed restaurants.
select restaurantid, count(*) as review_count from reviews group by restaurantid order by review_count desc;

-- 8. Find the most preferred payment method.
select paymentmethod, count(*) as usage_count from payments group by paymentmethod order by usage_count desc limit 1;

-- 9. List the top 5 restaurants by total revenue.
select restaurantid, sum(orderamount) as total_revenue from orders where orderstatus = 'Delivered' group by restaurantid order by total_revenue desc limit 5;

-- 10. Show the details of all cancelled orders along with the customer's and restaurant's names.
select o.orderid, o.orderdate, o.orderamount, c.firstname, c.lastname, r.name from orders o join customers c on o.customerid = c.customerid join restaurants r on o.restaurantid = r.restaurantid where o.orderstatus = 'Cancelled';
